name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d
        
    - name: Run flake8
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run flake8 ./
        
    - name: Run black
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run black --check ./
        
    - name: Run isort
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run isort --check-only ./